#!/bin/bash
#
# Data Download Helper Script
# Provides URLs and checks for available data sources
#

echo "======================================"
echo "Multi-City Data Download Helper"
echo "======================================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}📊 HAMBURG - Demographics Needed${NC}"
echo ""
echo "✅ Geodata: Already downloaded (104 Stadtteile)"
echo "🔍 Demographics: NEEDED"
echo ""
echo "Try these sources:"
echo "1. Statistik Nord:"
echo "   https://www.statistik-nord.de/zahlen-fakten/bevoelkerung-gebiet-wahlen/bevoelkerung"
echo ""
echo "2. Hamburg Transparency Portal:"
echo "   https://transparenz.hamburg.de/"
echo "   Search: 'Bevölkerung Stadtteile' or 'Einwohner Stadtteile'"
echo ""
echo "3. Regional Database:"
echo "   https://region.statistik-nord.de/"
echo ""
echo "What you need:"
echo "  - CSV or Excel file"
echo "  - ~104 rows (one per Stadtteil)"
echo "  - Columns: Stadtteil ID/Name, Population, Age groups"
echo ""
echo "Where to save: data/raw/hamburg/demographics.csv"
echo ""
echo "---"
echo ""

echo -e "${BLUE}🗺️ MUNICH - Geodata & Demographics Needed${NC}"
echo ""
echo "GEODATA:"
echo "1. Munich Geoportal WFS:"
echo "   https://geoportal.muenchen.de/geoserver/gsm/wfs"
echo ""
echo "   Test for available layers:"
echo "   curl -s 'https://geoportal.muenchen.de/geoserver/gsm/wfs?SERVICE=WFS&REQUEST=GetCapabilities' | grep -i bezirk"
echo ""
echo "2. Open Data München:"
echo "   https://opendata.muenchen.de/"
echo "   Search: 'Stadtbezirke' or 'Stadtbezirksgrenzen'"
echo ""
echo "3. Bayern Geoportal:"
echo "   https://geoportal.bayern.de/"
echo ""
echo "What you need:"
echo "  - Shapefile, GeoJSON, or WFS service"
echo "  - 25 Stadtbezirke (city districts)"
echo ""
echo "DEMOGRAPHICS:"
echo "1. Munich Statistics:"
echo "   https://www.muenchen.de/rathaus/Stadtinfos/Statistik/Bev%C3%B6lkerung.html"
echo ""
echo "2. Statistics Portal:"
echo "   https://www.muenchen.de/rathaus/stadtinfos/statistik/bevoelkerung"
echo ""
echo "What you need:"
echo "  - CSV or Excel file"
echo "  - 25 rows (one per Stadtbezirk)"
echo "  - Columns: Bezirk number/name, Population, Age groups"
echo ""
echo "Where to save:"
echo "  - Geodata: data/raw/munich/ (any format)"
echo "  - Demographics: data/raw/munich/demographics.csv"
echo ""
echo "---"
echo ""

echo -e "${YELLOW}💡 TIPS:${NC}"
echo ""
echo "1. Look for files dated 2023-2024 for most recent data"
echo "2. CSV/Excel files are easier than PDFs"
echo "3. For geodata, WFS services are best (auto-download)"
echo "4. Check file headers to identify column names"
echo "5. Don't worry about exact age groups - we can adapt!"
echo ""
echo "---"
echo ""

echo -e "${GREEN}🔧 ONCE YOU HAVE THE DATA:${NC}"
echo ""
echo "Hamburg:"
echo "  1. Save CSV to: data/raw/hamburg/demographics.csv"
echo "  2. Update cities/hamburg.config.ts with field names"
echo "  3. Run: ./scripts/process-city.sh hamburg"
echo ""
echo "Munich:"
echo "  1. Save geodata to: data/raw/munich/"
echo "  2. Save demographics to: data/raw/munich/demographics.csv"
echo "  3. Update cities/munich.config.ts with URLs & field names"
echo "  4. Run: ./scripts/process-city.sh munich"
echo ""
echo "======================================"
echo "Need help? Check the documentation:"
echo "  - QUICK_START.md"
echo "  - MULTI_CITY_README.md"
echo "======================================"


